Dieser Branch wurde angelegt, um zu Testen, ob sich die Exception beim Start durch einen einfachen Wrapper umgehen l√§sst
